!!poa.escenario.ScenarioConfig
name: "EscenarioPrueba"
description: "Ejemplo para hacer una configuración YAML"
fishMarket:
  name: "Lonja"
  config: "fishMarket.yaml"
sellers:
  - name: "Vendedor1"
    config: "sellerType1.yaml"
  - name: "Vendedor2"
    config: "sellerType1.yaml" 