!!poa.escenario.ScenarioConfig
name: "EscenarioPrueba"
description: "Ejemplo para hacer una configuración YAML"
fishMarket:
  name: "Lonja"
  config: "fishMarket.yaml"
buyers:
  - name: "Comprador1"
    config: "buyerType1.yaml"
  - name: "Comprador2"
    config: "buyerType1.yaml"
