!!poa.ontologia.Vendedor
productosParaVender:
  - kilos: 10.0
    pescado: "sardina"
    precio: 100.0
    precioReserva: 10.0
  - kilos: 5.0
    pescado: "bacalao"
    precio: 100.0
    precioReserva: 10.0